### ISSUE TITLE
Version to be used in a bundler

### ISSUE THREAD

**Issue by fakiolinho** [Bernardo-Castilho/WijmoReact#1]
Great work. Is there a version available which could be used with browserify?

**Comment by Bernardo-Castilho** [comment]
Glad you like it!

The current version uses static files, so it can be easily used with browseirify/webpack and any other bundles. You could simply merge all the wijmo js and the react interop into a single file and be good to go.

Let me know if you're interested and I'll build a sample to demonstrate.

In the near future, we plan to add support for different module systems to Wijmo (system, node, amd). That will provide additional options for loading things on demand and asynchronously.

**Comment by fakiolinho** [comment]
Yes, the truth is i 've already done this because my setup is ReactJS with browserify and babelify.

A sample would be awesome, thanks. My company has already an enterprise license so we were using your AngularJS flavor but we 've realised recently that the ReactJS alternative is even faster. That's why we are trying to make the switch. So i am glad i 've found this repo of yours.

**Comment by Bernardo-Castilho** [comment]
Nice to know you are using our products. In the next release we will include "official" interops for React and Vue. They are similar to the one included here but a little more evolved. I do plan to update this repo soon to synchronize it with the "official" version.

I also started with Angular and recently realized how nice React is. I hope all our users will appreciate having more options.

Thanks again for the feedback.
