### ISSUE TITLE
unmount returns an error

### ISSUE THREAD

**Issue by fakiolinho** [Bernardo-Castilho/WijmoReact#2]
Unmount gives me an error while navigating to another page. I think `_unmount()` should become:

```javascript
 function _unmount(component) {
    _getControl(component).dispose();
 }
```

Now you have `_getControl(this).dispose();` so `this` keyword in there doesn't refer to the component itself.

**Comment by Bernardo-Castilho** [comment]
You are right, of course. Thanks a lot for reporting this! Much appreciated!
